<?php switch($jenis){
	case "Home";
		include("selamatdatang.php");
		break;
	case "Artikel";
		include("vartikel.php");
		break;
	case "Isi Artikel";
		include("isi_artikel.php");
		break;
	case "Galeri";
		include("vgaleri.php");
		break;
	case "Komentar";
		include("vkomentar.php");
		break;
	case "Profil";
		include("profil.php");
		break;
	case "Kontak";
		include("kontak.php");
		break;
	case "Cari";
		include("cari.php");
		break;
	case "Admin";
		include("admin/home_admin.php");
		break;
	case "manajemen_artikel";
		include("admin/manajemen_artikel.php");
		break;
	case "edit_manajemen_artikel";
		include("admin/edit_manajemen_artikel.php");
		break;
	case "tambah_artikel";
		include("admin/tambah_artikel.php");
		break;
	case "manajemen_link";
		include("admin/manajemen_link.php");
		break;
	case "edit_link";
		include("admin/link/edit_link.php");
		break;
	case "tambah_link";
		include("admin/link/tambah_link.php");
		break;
	case "manajemen_galeri";
		include("admin/galeri/manajemen_galeri.php");
		break;
	case "tambah_galeri";
		include("admin/galeri/tambah_galeri.php");
		break;
	case "edit_galeri";
		include("admin/galeri/edit_galeri.php");
		break;
	case "manajemen_iklan";
		include("admin/iklan/manajemen_iklan.php");
		break;
	case "tambah_iklan";
		include("admin/iklan/tambah_iklan.php");
		break;
	case "edit_iklan";
		include("admin/iklan/edit_iklan.php");
		break;
	}
	?>